node {
    stage 'Build'
        git url: 'https://github.com/jfrogdev/project-examples.git'

    stage 'Artifactory configuration'
        def server = Artifactory.newServer('http://localhost:8081/artifactory', 'admin', 'password')
        def artifactoryGradle = Artifactory.newGradleBuild()
        artifactoryGradle.tool = 'gradle-3.1'
        artifactoryGradle.deployer repo:'ext-release-local', server: server
        artifactoryGradle.resolver repo:'remote-repos', server: server

    stage 'Exec Gradle'
        def buildInfo = artifactoryGradle.run rootDir: "gradle-examples/4/gradle-example-ci-server/", buildFile: 'build.gradle', tasks: 'clean -Dartifactory.publish.artifacts=false -Dartifactory.publish.buildInfo=false artifactoryPublish'
}
